servers:
  - id: alpha
    port: 3000
    url: localhost
    genFolder: 'source-generated'
    functions:
      - pattern: main
        method: http-get
      - pattern: toLowerCase
      - pattern: '*'
  - id: beta
    port: 3001
    url: localhost
    functions:
    - pattern: toUpperCase
    - pattern: split
    - pattern: join
