codeGenerationParameters:
  mode: single                    # single | watch
  inputFolder: 'src'              # monolith folder
  outputFolder: '../distributed'  # distributed folder
  cleanOutput: true               # delete output folder before?
  generateProjects: true          # generate new npm projects?
  generateDocker: true            # generate docker files for each server?
  # ignore:                         # ignore the following folders
  #   - "node_modules"
  #   - "main*"
  #   - "product.js"
default:
  rabbit:
    url: localhost
    port: 5672
servers:
  - id: alpha
    http:
      url: localhost
      port: 3000
    functions:
      - declarationPattern: 'saveProduct'
        method: rabbit
      - declarationPattern: 'saveCustomer'
        method: rabbit
  - id: beta
    http:
      url: localhost
      port: 3001
    functions:
    - declarationPattern: split
      callPatterns:
        - 'strUtils.split'
      method: rabbit
    - declarationPattern: log
      method: rabbit
  - id: gamma
    http:
      url: localhost
      port: 3002
    functions:
    - declarationPattern: join
      method: rabbit
    - declarationPattern: main
      method: http-get