servers:
  - id: alpha
    port: 3000
    url: localhost
    functions:
      - pattern: main
        method: get
      - pattern: toLowerCase
        method: get
  - id: beta
    port: 3001
    url: localhost
    functions:
    - pattern: toUpperCase
      method: get
    - pattern: split
      method: get
    - pattern: join
      method: get
