replicate:
  functions:
  - declarationPattern: '*'
servers:
  - id: alpha
    port: 3000
    url: localhost
    functions:
      - declarationPattern: '*Case'
        method: http-get
  - id: beta
    port: 3001
    url: localhost
    functions:
    - declarationPattern: split
      method: http-get
    - declarationPattern: join
      method: http-get
  - id: gamma
    port: 3002
    url: localhost
    functions:
    - declarationPattern: saveProduct
      method: http-get
    - declarationPattern: push