servers:
  - id: server1
    port: 3000
    url: url-server1
    rabbitmq:
      exchange: server1_exchange
      queue: server1_queue
      connectionUrl: amqp://localhost
  - id: server2
    port: 5001
    url: url-server2
    rabbitmq:
      exchange: server2_exchange
      queue: server2_queue
      connectionUrl: amqp://localhost
  - id: server3
    port: 5004
    url: url-server3
    rabbitmq:
      exchange: server3_exchange
      queue: server3_queue
      connectionUrl: amqp://localhost

functions:
  - name: sub
    server: server1
    parameters: 
      - name: a
        type: number
      - name: b
        type: number
  - name: sum
    server: server2
    parameters: 
      - name: a
        type: number
      - name: b
        type: number
  - name: rodeiSum
    server: server1
    parameters: 
      - name: a
        type: number
      - name: b
        type: number
  - name: main
    server: server3 
    parameters: []
