GET http://localhost:3000/entryPoint

###

POST http://localhost:3000/entryPoint

###

GET http://localhost:3001/findUserByEmail?email=daniel@email.com

###

GET http://localhost:3002/generateKey?prefix=abcd

###

GET http://localhost:3001/generateKey2?suffix=1234
