default:
  rabbit:
    url: myrabbit
    port: 5672
servers:
  - id: alpha
    http:
      url: alpha
      port: 3000
    functions:
      - declarationPattern: 'saveProduct'
        method: rabbit
      - declarationPattern: 'saveCustomer'
        method: rabbit
  - id: beta
    http:
      url: beta
      port: 3001
    functions:
    - declarationPattern: split
      callPatterns:
        - 'strUtils.split'
      method: http-get
    - declarationPattern: join
      method: http-post
    - declarationPattern: log
      method: http-post
  - id: gamma
    http:
      port: 3002
      url: gamma
    functions:
    - declarationPattern: main