# Prefixos dos arquivos de saída (sem a extensao .js)
project:
  name: ordenaListas

# Definição dos servidores
servers:
  - id: main
    port: 3000
    url: localhost
  - id: sort
    port: 8080
    url: localhost
  - id: random
    port: 5000
    url: localhost
  - id: impressao
    port: 1500
    url: localhost

# Definição das funções
functions:
  - name: main
    server: main
    parameters: []
    method: get
  - name: sorteiaNumero
    server: random
    parameters:
      - name: n 
        type: number
    method: get
  - name: sorteiaLista
    server: random
    parameters: []
    method: get
  - name: insertionSort
    server: sort
    parameters:
      - name: inputArr
        type: list
    method: post
  - name: imprimeLista
    server: impressao
    parameters:
      - name: msg
        type: string
      - name: lista
        type: list
    method: post