# Prefixos dos arquivos de saída (sem a extensao .js)
project:
  name: ordenaListas

# Definição dos servidores
servers:
  - id: server1
    port: 3000
    url: localhost
  - id: server2
    port: 5000
    url: localhost
  - id: server3
    port: 1111
    url: localhost
  - id: server4
    port: 2222
    url: localhost
  - id: server5
    port: 3333
    url: localhost

functions:
  - name: main
    server: server1
    parameters: []
    method: get
  - name: sorteiaNumero
    server: server2
    parameters:
      - name: n 
        type: number
    method: get
  - name: sorteiaLista
    server: server3
    parameters: []
    method: get
  - name: insertionSort
    server: server4
    parameters:
      - name: inputArr
        type: list
    method: post
  - name: imprimeLista
    server: server5
    parameters:
      - name: msg
        type: string
      - name: lista
        type: list
    method: post