# Prefixos dos arquivos de saída (sem a extensao .js)
project:
  name: ordenaListas

# Definição dos servidores
servers:
  - id: server1
    port: 3000
    url: localhost
  - id: server2
    port: 5000
    url: localhost
  - id: server3
    port: 1111
    url: localhost
  - id: server4
    port: 2222
    url: localhost
  - id: server5
    port: 3333
    url: localhost
  - id: gama
    port: 4444
    url: localhost
  - id: alfa
    port: 5555
    url: localhost

functions:
  - name: main
    server: server1
    parameters: []
    method: get
  - name: sorteiaNumero
    server: server2
    parameters:
      - name: x
        type: number
      - name: argTeste
        type: string
    method: get
  - name: sorteiaLista
    server: server4
    parameters: []
    method: post
  - name: insertionSort
    server: server4
    parameters:
      - name: inputArr
        type: list
    method: post
  - name: imprimeLista
    server: server5
    parameters:
      - name: msg
        type: string
      - name: lista
        type: list
    method: post
  - name: ordenaListas
    server: server2
    parameters:
      - name: lista
        type: list
      - name: metodo
        type: string
      - name: msg
        type: string
    method: post
  - name: selectionSort
    server: server4
    parameters:
      - name: arr
        type: list
    method: post
  - name: deTeste
    server: server1
    parameters:
      - name: booleano
        type: bool
    method: GET
  - name: somarNumeros
    server: gama
    parameters:
      - name: a
        type: number
      - name: b
        type: number
    method: POST
  - name: ehPar
    server: gama
    parameters:
      - name: numero
        type: number
    method: GET
  - name: multiplicaNumeros
    server: alfa
    parameters:
      - name: a
        type: number
      - name: b
        type: number
    method: GET
  - name: doisValores
    server: server3
    parameters:
      - name: a
        type: number
      - name: b
        type: number
    method: POST
  - name: inverterString
    server: server2
    parameters:
      - name: str
        type: string
    method: POST
  - name: imprimeTresValores
    server: alfa
    parameters:
      - name: value1
        type: number
      - name: value2
        type: number
      - name: value3
        type: string
    method: GET
  - name: randomZeroUm
    server: server5
    parameters: []
    method: POST
  - name: multiplicaLista
    server: server3
    parameters:
      - name: a
        type: number
      - name: b
        type: number
    method: GET
  - name: multiplicaListaPassada
    server: gama
    parameters:
      - name: lista
        type: list
    method: POST
