# Prefixos dos arquivos de saída (sem a extensao .js)
project:
  name: ordenaListas

# Definição dos servidores
servers:
  - id: main
    port: 3000
    url: localhost
  - id: random1
    port: 5000
    url: localhost

functions:
  - name: main
    server: main
    parameters: []
    method: get
  - name: sorteiaNumero
    server: random1
    parameters:
      - name: n 
        type: number
    method: get
  - name: sorteiaLista
    server: random1
    parameters: []
    method: get
  - name: insertionSort
    server: random1
    parameters:
      - name: inputArr
        type: list
    method: post
  - name: imprimeLista
    server: main
    parameters:
      - name: msg
        type: string
      - name: lista
        type: list
    method: post