# Prefixos dos arquivos de saída (sem a extensao .js)
project:
  name: ordenaListas

# Definição dos servidores
servers:
  - id: main
    port: 3000
    url: url-main
  - id: sort
    port: 8080
    url: url-sort
  - id: random1
    port: 5000
    url: url-random1
  - id: random2
    port: 1111
    url: url-random2
  - id: impressao
    port: 1500
    url: url-impressao

# Definição das funções
functions:
  - name: main
    server: main
    parameters: []
  - name: sorteiaNumero
    server: random2
    parameters:
      - name: n 
        type: number
  - name: sorteiaLista
    server: random1
    parameters: []
  - name: insertionSort
    server: sort
    parameters:
      - name: inputArr
        type: list
  - name: imprimeLista
    server: impressao
    parameters:
      - name: msg
        type: string
      - name: lista
        type: list