# Prefixos dos arquivos de saída (sem a extensao .js)
# project:
#   name: ordenaListas




# Definição dos servidores
servers:
  - id: server1
    port: 3000
    url: localhost
    rabbitmq:
      exchange: server1_exchange
      queue: server1_queue
      connectionUrl: amqp://localhost
  - id: server2
    port: 5000
    url: localhost
    rabbitmq:
      exchange: server2_exchange
      queue: server2_queue
      connectionUrl: amqp://localhost
  - id: server3
    port: 1111
    url: localhost
    rabbitmq:
      exchange: server3_exchange
      queue: server3_queue
      connectionUrl: amqp://localhost
  - id: server4
    port: 2222
    url: localhost
  - id: server5
    port: 3333
    url: localhost
  - id: gama
    port: 4444
    url: localhost
  - id: alfa
    port: 5555
    url: localhost
    rabbitmq:
      exchange: alfa_exchange
      queue: alfa_queue
      connectionUrl: amqp://localhost

# opcoes para method: post, get, rabbit
functions:
  - name: main
    server: server1
    parameters: []
    method: get
  - name: sorteiaNumero
    server: server2
    parameters:
      - name: x
        type: number
      - name: argTeste
        type: string
    method: get
  - name: sorteiaLista
    server: gama
    parameters: []
    method: post
  - name: insertionSort
    server: server2
    parameters:
      - name: inputArr
        type: list
    method: post
  - name: imprimeLista
    server: server5
    parameters:
      - name: msg
        type: string
      - name: lista
        type: list
    method: post
  - name: ordenaListas
    server: server2
    parameters:
      - name: lista
        type: list
      - name: metodo
        type: string
      - name: msg
        type: string
    method: post
  - name: selectionSort
    server: server4
    parameters:
      - name: arr
        type: list
    method: post
  - name: deTeste
    server: server4
    parameters:
      - name: booleano
        type: bool
    method: GET
  - name: somarNumeros
    server: gama
    parameters:
      - name: a
        type: number
      - name: b
        type: number
    method: get
  - name: ehPar
    server: gama
    parameters:
      - name: numero
        type: number
    method: POST
  - name: multiplicaNumeros
    server: alfa
    parameters:
      - name: a
        type: number
      - name: b
        type: number
    method: GET
  - name: doisValores
    server: server3
    parameters:
      - name: a
        type: number
      - name: b
        type: number
    method: POST
  - name: inverterString
    server: server2
    parameters:
      - name: str
        type: string
    method: POST
  - name: imprimeTresValores
    server: server1
    parameters:
      - name: value1
        type: number
      - name: value2
        type: number
      - name: value3
        type: string
    method: GET
  - name: randomZeroUm
    server: server5
    parameters: []
    method: POST
  - name: multiplicaLista
    server: server3
    parameters:
      - name: a
        type: number
      - name: b
        type: number
    method: GET
  - name: multiplicaListaPassada
    server: gama
    parameters:
      - name: lista
        type: list
    method: POST
  - name: deltaFunction
    server: server1
    parameters:
      - name: a
        type: number
      - name: b
        type: number
      - name: c
        type: number
    method: POST
  - name: testeDeltaMaiorQueZero
    server: alfa
    parameters:
      - name: delta
        type: number
    method: POST
  - name: calcularBhaskara
    server: server5
    parameters:
      - name: a
        type: number
      - name: b
        type: number
      - name: c
        type: number
    method: GET
  - name: fazTudoComLista
    server: server2
    parameters: []
    method: POST
  - name: subtraiNumero
    server: server3
    parameters: 
      - name: a
        type: number
      - name: b
        type: number
    method: GET
  - name: calculaQuadrado
    server: alfa
    parameters: 
      - name: a
        type: number
    method: rabbit
  - name: sub_rabbit
    server: server1
    parameters: 
      - name: a
        type: number
      - name: b
        type: number
    method: rabbit
  - name: sum_rabbit
    server: server2
    parameters: 
      - name: a
        type: number
      - name: b
        type: number
    method: rabbit
  - name: rodeiSum
    server: server1
    parameters: 
      - name: a
        type: number
      - name: b
        type: number
    method: rabbit
  - name: main_rabbit
    server: server3
    parameters: []
    method: rabbit
  - name: checkEhPositivo
    server: server1
    parameters:
      - name: x
        type: number
    method: rabbit