# servers definition
servers:
  - id: alfa
    port: 3000
    url: localhost
    rabbitmq: 
      connectionUrl: amqp://localhost
  - id: gama
    port: 3001
    url: localhost
    rabbitmq: 
      connectionUrl: amqp://localhost

# functions definition
functions:
  - name: isAEqualToB
    method: get
    server: alfa
  - name: sub
    method: post
    server: gama