services:

    alpha:
        build: ./alpha
        ports:
            - "3000:3000"
        restart: always

    beta:
        build: ./beta
        ports:
            - "3001:3001"
        restart: always