default:
  rabbit:
    url: myrabbit
    port: 5672
servers:
  - id: main
    http:
      url: localhost
      port: 3000
    functions:
      - declarationPattern: main
  - id: alpha
    functions:
      - declarationPattern: toUpperCaseString
        callPatterns:
          - toUpperCaseString
          - tuc
          - util.toUpperCaseString
        method: rabbit
  - id: beta
    functions:
      - declarationPattern: toLowerCaseString
        method: rabbit
        callPatterns:
          - toLowerCaseString
          - tlc
          - util.toLowerCaseString
  - id: gamma
    functions:
      - declarationPattern: print
        method: rabbit