version: '3'
services:
  rabbit:
    image: rabbitmq:3-management
    hostname: myrabbit
    ports:
      - 5672:5672 # For AMPQ connection
      - 8080:15672 # Web interface
  main:
    build: ./distributed-rabbit/main
    ports:
        - "3000:3000"
    restart: always
  alpha:
      build: ./distributed-rabbit/alpha
      restart: always
  beta:
      build: ./distributed-rabbit/beta
      restart: always
  gamma:
      build: ./distributed-rabbit/gamma
      restart: always