services:

    main:
        build: ./main

        ports:
            - "3000:3000"

        restart: always

    alpha:
        build: ./alpha

        restart: always

    beta:
        build: ./beta

        restart: always

    gamma:
        build: ./gamma

        restart: always